version: '3'
services:
  app:
    image: bparra/express-demo
    ports:
      - "3000:3000"
  redis:
    image : redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "~/CSC667/data:/data/cardgame"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
volumes:
  mongodata:
networks:
  network1:
  webnet:
